# Generated by Django 4.2.5 on 2023-11-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0006_remove_department_img_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
